const QUIZ_DATA_HTML = {
    'modulo-1': [
        { question: "O que significa HTML?", options: [{id:'a', text:"Hyper Text Markup Language"}, {id:'b', text:"High Tech Modern Language"}, {id:'c', text:"Hyper Transfer Markup Language"}, {id:'d', text:"Home Tool Markup Language"}], correct: 'a', explanation: "✅ HTML é a linguagem de marcação padrão para criar páginas web." },
        { question: "Qual é a versão atual do HTML?", options: [{id:'a', text:"HTML4"}, {id:'b', text:"HTMLX"}, {id:'c', text:"HTML5"}, {id:'d', text:"HTML2025"}], correct: 'c', explanation: "✅ HTML5 é a versão mais recente e amplamente utilizada." },
        { question: "Qual tag define a raiz de um documento HTML?", options: [{id:'a', text:"<head>"}, {id:'b', text:"<body>"}, {id:'c', text:"<html>"}, {id:'d', text:"<root>"}], correct: 'c', explanation: "✅ A tag <html> envolve todo o conteúdo da página." },
        { question: "Onde ficam as metainformações do site?", options: [{id:'a', text:"<body>"}, {id:'b', text:"<footer>"}, {id:'c', text:"<head>"}, {id:'d', text:"<meta>"}], correct: 'c', explanation: "✅ O <head> contém informações que não aparecem diretamente na página." },
        { question: "Qual tag é usada para o título da aba do navegador?", options: [{id:'a', text:"<h1>"}, {id:'b', text:"<tab>"}, {id:'c', text:"<title>"}, {id:'d', text:"<head>"}], correct: 'c', explanation: "✅ <title> define o nome que aparece na aba do browser." },
        { question: "Para que serve o <!DOCTYPE html>?", options: [{id:'a', text:"Para estilizar a página"}, {id:'b', text:"Para informar ao browser que o documento é HTML5"}, {id:'c', text:"Para criar um link"}, {id:'d', text:"Para inserir uma imagem"}], correct: 'b', explanation: "✅ É a declaração necessária no topo de cada documento HTML5." },
        { question: "Qual atributo define o idioma da página na tag <html>?", options: [{id:'a', text:"language"}, {id:'b', text:"src"}, {id:'c', text:"lang"}, {id:'d', text:"href"}], correct: 'c', explanation: "✅ O atributo lang='pt-PT' ajuda motores de busca e leitores de ecrã." },
        { question: "Qual tag define o corpo visível do documento?", options: [{id:'a', text:"<content>"}, {id:'b', text:"<main>"}, {id:'c', text:"<body>"}, {id:'d', text:"<section>"}], correct: 'c', explanation: "✅ Tudo o que vês no browser está dentro do <body>." },
        { question: "O que é uma tag 'self-closing'?", options: [{id:'a', text:"Uma tag que se fecha sozinha (ex: <br>)"}, {id:'b', text:"Uma tag que não pode ser usada"}, {id:'c', text:"Uma tag que fecha o browser"}, {id:'d', text:"Uma tag de comentário"}], correct: 'a', explanation: "✅ Tags como <br>, <img> e <hr> não precisam de tag de fecho separada." },
        { question: "Como se escreve um comentário em HTML?", options: [{id:'a', text:"// comentário"}, {id:'b', text:"/* comentário */"}, {id:'c', text:"<!-- comentário -->"}, {id:'d', text:"# comentário"}], correct: 'c', explanation: "✅ Comentários HTML usam a sintaxe <!-- -->." }
    ],
    'modulo-2': [
        { question: "Qual tag representa o cabeçalho de uma secção ou página?", options: [{id:'a', text:"<head>"}, {id:'b', text:"<header>"}, {id:'c', text:"<top>"}, {id:'d', text:"<nav>"}], correct: 'b', explanation: "✅ <header> é um elemento semântico para introduções ou navegação." },
        { question: "Qual elemento é usado para o menu de navegação?", options: [{id:'a', text:"<ul>"}, {id:'b', text:"<menu>"}, {id:'c', text:"<nav>"}, {id:'d', text:"<links>"}], correct: 'c', explanation: "✅ <nav> define um bloco de links de navegação." },
        { question: "Para que serve a tag <main>?", options: [{id:'a', text:"Para o conteúdo principal e único da página"}, {id:'b', text:"Para o rodapé"}, {id:'c', text:"Para anúncios laterais"}, {id:'d', text:"Para o menu"}], correct: 'a', explanation: "✅ <main> deve conter o conteúdo central que não se repete no site." },
        { question: "Qual tag define um conteúdo independente e auto-contido (ex: post de blog)?", options: [{id:'a', text:"<section>"}, {id:'b', text:"<div>"}, {id:'c', text:"<article>"}, {id:'d', text:"<aside>"}], correct: 'c', explanation: "✅ <article> é ideal para conteúdos que fazem sentido sozinhos." },
        { question: "Para que serve o <aside>?", options: [{id:'a', text:"Para o rodapé"}, {id:'b', text:"Para conteúdo relacionado mas indireto (sidebar)"}, {id:'c', text:"Para o título principal"}, {id:'d', text:"Para links externos"}], correct: 'b', explanation: "✅ <aside> é frequentemente usado para barras laterais." },
        { question: "Qual tag representa o rodapé?", options: [{id:'a', text:"<bottom>"}, {id:'b', text:"<end>"}, {id:'c', text:"<footer>"}, {id:'d', text:"<base>"}], correct: 'c', explanation: "✅ <footer> contém informações de contacto, copyright, etc." },
        { question: "Qual a diferença entre <div> e <section>?", options: [{id:'a', text:"Nenhuma"}, {id:'b', text:"<div> é genérico, <section> tem significado temático"}, {id:'c', text:"<section> é mais rápido"}, {id:'d', text:"<div> só serve para texto"}], correct: 'b', explanation: "✅ Devemos preferir <section> para agrupar conteúdo relacionado." },
        { question: "Quantos <h1> devem existir idealmente por página?", options: [{id:'a', text:"Quantos quiseres"}, {id:'b', text:"Nenhum"}, {id:'c', text:"Apenas um"}, {id:'d', text:"Exatamente seis"}], correct: 'c', explanation: "✅ Para SEO e acessibilidade, usa apenas um <h1> principal." },
        { question: "Qual tag define um parágrafo?", options: [{id:'a', text:"<text>"}, {id:'b', text:"<para>"}, {id:'c', text:"<p>"}, {id:'d', text:"<span>"}], correct: 'c', explanation: "✅ A tag <p> é a base para blocos de texto." },
        { question: "Para que serve a tag <figure>?", options: [{id:'a', text:"Para fazer contas"}, {id:'b', text:"Para agrupar uma imagem e a sua legenda (<figcaption>)"}, {id:'c', text:"Para desenhar círculos"}, {id:'d', text:"Para formatar números"}], correct: 'b', explanation: "✅ <figure> é a forma semântica de associar imagens a descrições." }
    ],
    'modulo-3': [
        { question: "Qual tag inicia um formulário?", options: [{id:'a', text:"<input>"}, {id:'b', text:"<form>"}, {id:'c', text:"<label>"}, {id:'d', text:"<action>"}], correct: 'b', explanation: "✅ <form> envolve todos os campos de entrada." },
        { question: "Qual atributo do <form> define para onde os dados são enviados?", options: [{id:'a', text:"method"}, {id:'b', text:"target"}, {id:'c', text:"action"}, {id:'d', text:"src"}], correct: 'c', explanation: "✅ O atributo 'action' contém o URL de destino dos dados." },
        { question: "Qual 'type' de input cria uma caixa de seleção única (várias opções, escolhe uma)?", options: [{id:'a', text:"checkbox"}, {id:'b', text:"text"}, {id:'c', text:"radio"}, {id:'d', text:"select"}], correct: 'c', explanation: "✅ Inputs do tipo 'radio' permitem escolher apenas uma opção de um grupo." },
        { question: "Para que serve a tag <label>?", options: [{id:'a', text:"Para dar estilo ao botão"}, {id:'b', text:"Para associar um texto a um input"}, {id:'c', text:"Para criar uma tabela"}, {id:'d', text:"Para validar o email"}], correct: 'b', explanation: "✅ <label> melhora a acessibilidade e a área de clique." },
        { question: "Qual atributo associa um <label> a um <input>?", options: [{id:'a', text:"id"}, {id:'b', text:"name"}, {id:'c', text:"for"}, {id:'d', text:"rel"}], correct: 'c', explanation: "✅ O atributo 'for' do label deve ser igual ao 'id' do input." },
        { question: "Como crias um campo de texto longo de várias linhas?", options: [{id:'a', text:"<input type='big'>"}, {id:'b', text:"<textarea>"}, {id:'c', text:"<text>"}, {id:'d', text:"<p editable>"}], correct: 'b', explanation: "✅ <textarea> é usado para mensagens, comentários, etc." },
        { question: "Qual atributo torna um campo de preenchimento obrigatório?", options: [{id:'a', text:"must"}, {id:'b', text:"validate"}, {id:'c', text:"required"}, {id:'d', text:"important"}], correct: 'c', explanation: "✅ O atributo boolean 'required' impede o envio se o campo estiver vazio." },
        { question: "Qual type de input é usado para senhas (esconde os carateres)?", options: [{id:'a', text:"hidden"}, {id:'b', text:"secret"}, {id:'c', text:"password"}, {id:'d', text:"lock"}], correct: 'c', explanation: "✅ type='password' mostra pontos ou asteriscos em vez do texto." },
        { question: "Para que serve o elemento <select>?", options: [{id:'a', text:"Para selecionar ficheiros"}, {id:'b', text:"Para criar uma lista pendente (dropdown)"}, {id:'c', text:"Para escolher cores"}, {id:'d', text:"Para marcar texto"}], correct: 'b', explanation: "✅ <select> com elementos <option> cria menus de escolha." },
        { question: "Qual o valor padrão do atributo 'method' num form?", options: [{id:'a', text:"POST"}, {id:'b', text:"GET"}, {id:'c', text:"SEND"}, {id:'d', text:"PUSH"}], correct: 'b', explanation: "✅ Se não for especificado, o browser usa o método GET." }
    ],
    'modulo-4': [
        { question: "Qual tag é usada para inserir uma imagem?", options: [{id:'a', text:"<picture>"}, {id:'b', text:"<src>"}, {id:'c', text:"<img>"}, {id:'d', text:"<image>"}], correct: 'c', explanation: "✅ <img> é a tag básica para imagens." },
        { question: "Qual atributo define o caminho da imagem?", options: [{id:'a', text:"href"}, {id:'b', text:"link"}, {id:'c', text:"src"}, {id:'d', text:"alt"}], correct: 'c', explanation: "✅ 'src' significa 'source' (origem)." },
        { question: "Para que serve o atributo 'alt' na imagem?", options: [{id:'a', text:"Para mudar o tamanho"}, {id:'b', text:"Para texto alternativo (acessibilidade e erro de carga)"}, {id:'c', text:"Para alinhar à esquerda"}, {id:'d', text:"Para criar um link"}], correct: 'b', explanation: "✅ O 'alt' é obrigatório para um HTML de qualidade e acessível." },
        { question: "Qual tag é usada para inserir vídeo?", options: [{id:'a', text:"<movie>"}, {id:'b', text:"<media>"}, {id:'c', text:"<video>"}, {id:'d', text:"<player>"}], correct: 'c', explanation: "✅ <video> permite reproduzir vídeos nativamente." },
        { question: "Qual atributo do <video> permite ver os botões de Play/Pause?", options: [{id:'a', text:"buttons"}, {id:'b', text:"show"}, {id:'c', text:"controls"}, {id:'d', text:"play"}], correct: 'c', explanation: "✅ Sem o atributo 'controls', o vídeo pode não ser controlável pelo utilizador." },
        { question: "Para que serve a tag <audio>?", options: [{id:'a', text:"Para ouvir rádio"}, {id:'b', text:"Para inserir ficheiros de som"}, {id:'c', text:"Para comandos de voz"}, {id:'d', text:"Para traduzir texto"}], correct: 'b', explanation: "✅ <audio> funciona de forma similar à tag <video>." },
        { question: "O que é o elemento <canvas>?", options: [{id:'a', text:"Uma moldura para fotos"}, {id:'b', text:"Uma área para desenhar gráficos via JavaScript"}, {id:'c', text:"Um tipo de botão"}, {id:'d', text:"Um mapa interativo"}], correct: 'b', explanation: "✅ <canvas> é usado para jogos e visualizações de dados dinâmicas." },
        { question: "Qual tag é usada para incorporar outro site ou mapa?", options: [{id:'a', text:"<frame>"}, {id:'b', text:"<embed>"}, {id:'c', text:"<iframe>"}, {id:'d', text:"<object>"}], correct: 'c', explanation: "✅ <iframe> (inline frame) incorpora documentos externos." },
        { question: "Qual a diferença entre <img> e <picture>?", options: [{id:'a', text:"Nenhuma"}, {id:'b', text:"<picture> permite várias fontes para diferentes ecrãs (Art Direction)"}, {id:'c', text:"<img> é mais moderno"}, {id:'d', text:"<picture> só funciona com PNG"}], correct: 'b', explanation: "✅ <picture> é excelente para imagens responsivas avançadas." },
        { question: "O que faz o atributo 'autoplay' num vídeo?", options: [{id:'a', text:"Faz o vídeo parar"}, {id:'b', text:"Inicia o vídeo sozinho (geralmente precisa de 'muted')"}, {id:'c', text:"Muda a cor do vídeo"}, {id:'d', text:"Aumenta a velocidade"}], correct: 'b', explanation: "✅ O autoplay inicia o vídeo mal a página carrega." }
    ],
    'modulo-5': [
        { question: "O que significa 'Acessibilidade Web' (A11y)?", options: [{id:'a', text:"Ter internet rápida"}, {id:'b', text:"Garantir que todos, incluindo pessoas com deficiências, podem usar o site"}, {id:'c', text:"Ter um site gratuito"}, {id:'d', text:"Usar muitas cores"}], correct: 'b', explanation: "✅ Acessibilidade é sobre inclusão digital." },
        { question: "O que são atributos ARIA?", options: [{id:'a', text:"Tags de estilo"}, {id:'b', text:"Accessible Rich Internet Applications - ajudam leitores de ecrã"}, {id:'c', text:"Comandos de som"}, {id:'d', text:"Filtros de imagem"}], correct: 'b', explanation: "✅ ARIA fornece contexto extra quando o HTML semântico não chega." },
        { question: "Qual o principal benefício do HTML Semântico para SEO?", options: [{id:'a', text:"O site fica mais bonito"}, {id:'b', text:"Ajuda o Google a entender a hierarquia e importância do conteúdo"}, {id:'c', text:"O site carrega mais rápido"}, {id:'d', text:"Evita vírus"}], correct: 'b', explanation: "✅ O Google 'lê' melhor o teu site se usares as tags corretas." },
        { question: "Para que serve a meta tag 'description'?", options: [{id:'a', text:"Para descrever imagens"}, {id:'b', text:"Para o resumo que aparece nos resultados do Google"}, {id:'c', text:"Para o título da página"}, {id:'d', text:"Para o nome do autor"}], correct: 'b', explanation: "✅ É o pequeno texto que convence o utilizador a clicar no teu site no Google." },
        { question: "O que é o atributo 'tabindex'?", options: [{id:'a', text:"Uma lista de abas"}, {id:'b', text:"Controla a ordem de navegação via teclado (tecla TAB)"}, {id:'c', text:"Um índice de cores"}, {id:'d', text:"Um comando para fechar abas"}], correct: 'b', explanation: "✅ Importante para quem navega sem rato." },
        { question: "Qual a importância do contraste de cores?", options: [{id:'a', text:"Apenas estética"}, {id:'b', text:"Garantir que o texto é legível para pessoas com baixa visão"}, {id:'c', text:"Poupar bateria"}, {id:'d', text:"Seguir a moda"}], correct: 'b', explanation: "✅ Um bom contraste é um pilar da acessibilidade." },
        { question: "Por que não devemos usar 'Clique Aqui' como texto de link?", options: [{id:'a', text:"É proibido"}, {id:'b', text:"Não é descritivo para leitores de ecrã nem para SEO"}, {id:'c', text:"É muito curto"}, {id:'d', text:"Fica feio"}], correct: 'b', explanation: "✅ Links devem descrever para onde levam (ex: 'Ver Preços')." },
        { question: "O que faz a tag <meta charset='UTF-8'>?", options: [{id:'a', text:"Define o tamanho do site"}, {id:'b', text:"Define a codificação de carateres (suporte a acentos)"}, {id:'c', text:"Muda a cor da fonte"}, {id:'d', text:"Acelera o site"}], correct: 'b', explanation: "✅ Garante que os carateres especiais aparecem corretamente." },
        { question: "Para que serve o atributo 'role'?", options: [{id:'a', text:"Para definir papéis de utilizador"}, {id:'b', text:"Para dizer ao leitor de ecrã que tipo de elemento é aquele (ex: role='button')"}, {id:'c', text:"Para criar animações"}, {id:'d', text:"Para rodar elementos"}], correct: 'b', explanation: "✅ Reforça o significado de elementos não semânticos." },
        { question: "O que é um Sitemap?", options: [{id:'a', text:"Um mapa para GPS"}, {id:'b', text:"Um ficheiro XML que lista todas as páginas do site para o Google"}, {id:'c', text:"Um design do site"}, {id:'d', text:"Uma pasta de imagens"}], correct: 'b', explanation: "✅ Facilita a indexação do site pelos motores de busca." }
    ],
    'modulo-6': [
        { question: "Qual a primeira fase na criação de um projeto web?", options: [{id:'a', text:"Escrever CSS"}, {id:'b', text:"Planear a estrutura e o conteúdo"}, {id:'c', text:"Comprar o domínio"}, {id:'d', text:"Fazer o upload"}], correct: 'b', explanation: "✅ Um bom planeamento poupa horas de código." },
        { question: "O que significa 'Mobile-First'?", options: [{id:'a', text:"Criar apps para telemóvel primeiro"}, {id:'b', text:"Desenhar para ecrãs pequenos e depois expandir para desktop"}, {id:'c', text:"Usar apenas telemóveis"}, {id:'d', text:"O site só funciona em mobile"}], correct: 'b', explanation: "✅ É a estratégia padrão da indústria moderna." },
        { question: "Qual ficheiro é considerado a porta de entrada de qualquer site?", options: [{id:'a', text:"main.html"}, {id:'b', text:"home.html"}, {id:'c', text:"index.html"}, {id:'d', text:"start.html"}], correct: 'c', explanation: "✅ Os servidores procuram por index.html por defeito." },
        { question: "O que deves validar antes de entregar um projeto?", options: [{id:'a', text:"Apenas se abre"}, {id:'b', text:"Links, formulários, responsividade e erros de consola"}, {id:'c', text:"Se o Google gosta"}, {id:'d', text:"Se as cores combinam"}], correct: 'b', explanation: "✅ Testes rigorosos garantem a qualidade profissional." },
        { question: "Como podes hospedar o teu projeto final gratuitamente?", options: [{id:'a', text:"Não é possível"}, {id:'b', text:"GitHub Pages ou Vercel"}, {id:'c', text:"No Google Drive"}, {id:'d', text:"Por email"}], correct: 'b', explanation: "✅ Existem várias plataformas excelentes para sites estáticos." },
        { question: "O que é o 'DOM' (Document Object Model)?", options: [{id:'a', text:"Um tipo de computador"}, {id:'b', text:"A representação do HTML que o browser usa para interagir com JS"}, {id:'c', text:"Uma marca de sapatos"}, {id:'d', text:"Um motor de busca"}], correct: 'b', explanation: "✅ O DOM permite que o JavaScript mude o HTML em tempo real." },
        { question: "Qual a importância de usar nomes de classes claros?", options: [{id:'a', text:"Para o CSS ser mais rápido"}, {id:'b', text:"Para o código ser legível e fácil de manter"}, {id:'c', text:"Para o Google indexar"}, {id:'d', text:"Para evitar hackers"}], correct: 'b', explanation: "✅ Código limpo é código profissional." },
        { question: "O que deves fazer se o teu HTML não estiver a funcionar como esperado?", options: [{id:'a', text:"Desistir"}, {id:'b', text:"Usar as DevTools (F12) para inspecionar os elementos"}, {id:'c', text:"Apagar tudo"}, {id:'d', text:"Mudar de browser"}], correct: 'b', explanation: "✅ Inspecionar é a melhor forma de encontrar erros." },
        { question: "Por que deves separar HTML, CSS e JS?", options: [{id:'a', text:"Para ter mais ficheiros"}, {id:'b', text:"Organização e facilidade de manutenção (Separação de Preocupações)"}, {id:'c', text:"O browser obriga"}, {id:'d', text:"Para carregar mais rápido"}], correct: 'b', explanation: "✅ Mantém o projeto escalável e limpo." },
        { question: "Qual o sentimento após terminar o teu primeiro projeto HTML5?", options: [{id:'a', text:"Cansaço"}, {id:'b', text:"Orgulho de ser um Web Developer Elite 🚀"}, {id:'c', text:"Dúvida"}, {id:'d', text:"Fome"}], correct: 'b', explanation: "✅ Parabéns! Deste o primeiro passo real no mundo do desenvolvimento web." }
    ]
};

if (typeof QUIZ_DATA !== 'undefined') {
    Object.assign(QUIZ_DATA, QUIZ_DATA_HTML);
} else {
    var QUIZ_DATA = QUIZ_DATA_HTML;
}
