const QUIZ_DATA_HTML = {
    'modulo-0': [
        { question: "Qual é a extensão padrão para ficheiros HTML?", options: [{id:'a', text:".html ou .htm"}, {id:'b', text:".web"}, {id:'c', text:".site"}, {id:'d', text:".hml"}], correct: 'a', explanation: "A extensão .html é o padrão universal, mas .htm também é válido (herança do DOS)." },
        { question: "Para que serve o atalho '!' no VS Code seguido de TAB?", options: [{id:'a', text:"Para criar um comentário"}, {id:'b', text:"Para gerar a estrutura base de um documento HTML5"}, {id:'c', text:"Para instalar uma extensão"}, {id:'d', text:"Para abrir o terminal"}], correct: 'b', explanation: "O Emmet '!' gera toda a estrutura HTML5 padrão com doctype, head e body." },
        { question: "Qual é a função da tag <meta charset='UTF-8'>?", options: [{id:'a', text:"Define o tamanho da fonte"}, {id:'b', text:"Define a codificação de caracteres para suportar acentos"}, {id:'c', text:"Cria um novo separador no browser"}, {id:'d', text:"Carrega CSS externo"}], correct: 'b', explanation: "UTF-8 permite usar caracteres portugueses (ã, ç, õ) sem problemas de exibição." },
        { question: "Qual atalho do VS Code serve para guardar o ficheiro?", options: [{id:'a', text:"Ctrl + C"}, {id:'b', text:"Ctrl + S"}, {id:'c', text:"Ctrl + P"}, {id:'d', text:"Ctrl + V"}], correct: 'b', explanation: "Ctrl + S é o atalho universal para guardar alterações no VS Code." },
        { question: "O que é o Live Server no VS Code?", options: [{id:'a', text:"Um editor de imagens"}, {id:'b', text:"Uma extensão que atualiza a página automaticamente"}, {id:'c', text:"Um gestor de ficheiros"}, {id:'d', text:"Um terminal integrado"}], correct: 'b', explanation: "O Live Server atualiza o navegador automaticamente quando guardas o código." }
    ],
    'modulo-1': [
        { question: "O que significa HTML?", options: [{id:'a', text:"Hyper Text Markup Language"}, {id:'b', text:"High Tech Modern Language"}, {id:'c', text:"Hyper Transfer Markup Language"}, {id:'d', text:"Home Tool Markup Language"}], correct: 'a', explanation: "HTML é a linguagem de marcação padrão para criar páginas web." },
        { question: "Qual é a versão atual do HTML?", options: [{id:'a', text:"HTML4"}, {id:'b', text:"HTMLX"}, {id:'c', text:"HTML5"}, {id:'d', text:"HTML2025"}], correct: 'c', explanation: "HTML5 é a versão mais recente e amplamente utilizada." },
        { question: "Qual tag define a raiz de um documento HTML?", options: [{id:'a', text:"<head>"}, {id:'b', text:"<body>"}, {id:'c', text:"<html>"}, {id:'d', text:"<root>"}], correct: 'c', explanation: "A tag <html> envolve todo o conteúdo da página." },
        { question: "Qual tag contém as configurações invisíveis da página?", options: [{id:'a', text:"<body>"}, {id:'b', text:"<header>"}, {id:'c', text:"<head>"}, {id:'d', text:"<main>"}], correct: 'c', explanation: "O <head> guarda metadados, título e links para CSS/JS." },
        { question: "Qual tag contém todo o conteúdo visível da página?", options: [{id:'a', text:"<html>"}, {id:'b', text:"<head>"}, {id:'c', text:"<body>"}, {id:'d', text:"<footer>"}], correct: 'c', explanation: "O <body> contém tudo o que aparece no navegador." }
    ],
    'modulo-2': [
        { question: "Qual é o nível de título mais importante em HTML?", options: [{id:'a', text:"<h6>"}, {id:'b', text:"<h0>"}, {id:'c', text:"<h1>"}, {id:'d', text:"<title>"}], correct: 'c', explanation: "O <h1> é o título principal da página, deve haver apenas um por página." },
        { question: "Qual tag cria um parágrafo de texto?", options: [{id:'a', text:"<text>"}, {id:'b', text:"<p>"}, {id:'c', text:"<par>"}, {id:'d', text:"<paragraph>"}], correct: 'b', explanation: "A tag <p> define um parágrafo e adiciona espaçamento automático." },
        { question: "Qual tag cria uma quebra de linha?", options: [{id:'a', text:"<break>"}, {id:'b', text:"<newline>"}, {id:'c', text:"<br>"}, {id:'d', text:"<lb>"}], correct: 'c', explanation: "A tag <br> força uma quebra de linha sem criar novo parágrafo." },
        { question: "Qual tag cria texto em negrito semanticamente?", options: [{id:'a', text:"<bold>"}, {id:'b', text:"<strong>"}, {id:'c', text:"<b>"}, {id:'d', text:"<negrito>"}], correct: 'b', explanation: "A tag <strong> indica importância semântica, não apenas apresentação." },
        { question: "Qual tag cria texto em itálico semanticamente?", options: [{id:'a', text:"<i>"}, {id:'b', text:"<italic>"}, {id:'c', text:"<em>"}, {id:'d', text:"<斜体>"}], correct: 'c', explanation: "A tag <em> indica ênfase semântica, não apenas estilo visual." }
    ],
    'modulo-3': [
        { question: "Qual tag cria uma lista não ordenada?", options: [{id:'a', text:"<ol>"}, {id:'b', text:"<ul>"}, {id:'c', text:"<list>"}, {id:'d', text:"<ulist>"}], correct: 'b', explanation: "A tag <ul> cria uma lista com marcadores (bullets)." },
        { question: "Qual tag cria uma lista ordenada (numerada)?", options: [{id:'a', text:"<ul>"}, {id:'b', text:"<ol>"}, {id:'c', text:"<list>"}, {id:'d', text:"<ordered>"}], correct: 'b', explanation: "A tag <ol> cria uma lista com numeração automática (1, 2, 3...)." },
        { question: "Qual atributo define o destino de um link?", options: [{id:'a', text:"link"}, {id:'b', text:"src"}, {id:'c', text:"href"}, {id:'d', text:"target"}], correct: 'c', explanation: "O atributo href especifica o URL de destino do link." },
        { question: "Para que serve o atributo target='_blank'?", options: [{id:'a', text:"Abre o link numa nova aba"}, {id:'b', text:"Fecha a aba atual"}, {id:'c', text:"Abre o link em popup"}, {id:'d', text:"Atualiza a página"}], correct: 'a', explanation: "target='_blank' abre o link numa nova aba ou janela do navegador." },
        { question: "Qual tag cria um hyperlink?", options: [{id:'a', text:"<link>"}, {id:'b', text:"<a>"}, {id:'c', text:"<href>"}, {id:'d', text:"<url>"}], correct: 'b', explanation: "A tag <a> (anchor) cria links clicáveis para outras páginas ou secções." }
    ],
    'modulo-4': [
        { question: "Qual tag é usada para inserir uma imagem?", options: [{id:'a', text:"<picture>"}, {id:'b', text:"<src>"}, {id:'c', text:"<img>"}, {id:'d', text:"<image>"}], correct: 'c', explanation: "A tag <img> é a tag básica para inserir imagens." },
        { question: "Qual atributo define o caminho da imagem?", options: [{id:'a', text:"href"}, {id:'b', text:"link"}, {id:'c', text:"src"}, {id:'d', text:"alt"}], correct: 'c', explanation: "O atributo src (source) especifica o URL ou caminho da imagem." },
        { question: "Para que serve o atributo 'alt' na tag img?", options: [{id:'a', text:"Define o tamanho da imagem"}, {id:'b', text:"Define texto alternativo para acessibilidade"}, {id:'c', text:"Define a cor de fundo"}, {id:'d', text:"Define a animação"}], correct: 'b', explanation: "O alt fornece descrição da imagem para leitores de ecrã e SEO." },
        { question: "Qual tag agrupar uma imagem com a sua legenda?", options: [{id:'a', text:"<img-group>"}, {id:'b', text:"<figure>"}, {id:'c', text:"<caption>"}, {id:'d', text:"<gallery>"}], correct: 'b', explanation: "A tag <figure> agrupa a imagem com a legenda (<figcaption>) semanticamente." },
        { question: "Qual é o formato de imagem mais recomendado para web?", options: [{id:'a', text:"BMP"}, {id:'b', text:"WebP"}, {id:'c', text:"TIFF"}, {id:'d', text:"RAW"}], correct: 'b', explanation: "WebP oferece compressão superior com qualidade comparável a JPEG/PNG." }
    ],
    'modulo-5': [
        { question: "Qual tag inicia uma tabela em HTML?", options: [{id:'a', text:"<table>"}, {id:'b', text:"<grid>"}, {id:'c', text:"<sheet>"}, {id:'d', text:"<tr>"}], correct: 'a', explanation: "A tag <table> é o elemento raiz de uma tabela HTML." },
        { question: "Qual tag define o cabeçalho de uma tabela?", options: [{id:'a', text:"<td>"}, {id:'b', text:"<th>"}, {id:'c', text:"<tr>"}, {id:'d', text:"<thead>"}], correct: 'b', explanation: "A tag <th> define uma célula de cabeçalho, aparece em negrito por defeito." },
        { question: "Qual tag define uma linha na tabela?", options: [{id:'a', text:"<td>"}, {id:'b', text:"<th>"}, {id:'c', text:"<tr>"}, {id:'d', text:"<row>"}], correct: 'c', explanation: "A tag <tr> (table row) define uma linha horizontal da tabela." },
        { question: "Qual atributo une várias células horizontalmente?", options: [{id:'a', text:"rowspan"}, {id:'b', text:"colspan"}, {id:'c', text:"merge"}, {id:'d', text:"span"}], correct: 'b', explanation: "colspan='n' faz uma célula ocupar n colunas horizontalmente." },
        { question: "Qual tag cria a legenda de uma tabela?", options: [{id:'a', text:"<legend>"}, {id:'b', text:"<caption>"}, {id:'c', text:"<title>"}, {id:'d', text:"<header>"}], correct: 'b', explanation: "A tag <caption> cria uma legenda visível acima ou abaixo da tabela." }
    ],
    'modulo-6': [
        { question: "Qual tag inicia um formulário em HTML?", options: [{id:'a', text:"<input>"}, {id:'b', text:"<form>"}, {id:'c', text:"<label>"}, {id:'d', text:"<button>"}], correct: 'b', explanation: "A tag <form> envolve todos os campos de entrada do formulário." },
        { question: "Qual atributo torna um campo obrigatório?", options: [{id:'a', text:"must"}, {id:'b', text:"validate"}, {id:'c', text:"required"}, {id:'d', text:"important"}], correct: 'c', explanation: "O atributo boolean 'required' impede o envio se o campo estiver vazio." },
        { question: "Qual é o tipo de input para caixas de texto?", options: [{id:'a', text:"textbox"}, {id:'b', text:"text"}, {id:'c', text:"input"}, {id:'d', text:"write"}], correct: 'b', explanation: "input type='text' cria uma caixa de texto de uma linha." },
        { question: "Qual tag associa um rótulo ao campo do formulário?", options: [{id:'a', text:"<field>"}, {id:'b', text:"<label>"}, {id:'c', text:"<input>"}, {id:'d', text:"<span>"}], correct: 'b', explanation: "A tag <label> associa semanticamente o texto ao campo para acessibilidade." },
        { question: "Qual atributo define o nome do campo para o servidor?", options: [{id:'a', text:"id"}, {id:'b', text:"name"}, {id:'c', text:"class"}, {id:'d', text:"value"}], correct: 'b', explanation: "O atributo 'name' define a chave que será enviada ao servidor." }
    ],
    'modulo-7': [
        { question: "Qual tag representa o cabeçalho de uma secção ou página?", options: [{id:'a', text:"<head>"}, {id:'b', text:"<header>"}, {id:'c', text:"<top>"}, {id:'d', text:"<nav>"}], correct: 'b', explanation: "<header> é um elemento semântico para introduções ou navegação." },
        { question: "Para que serve a tag <main>?", options: [{id:'a', text:"Para o conteúdo principal e único da página"}, {id:'b', text:"Para o rodapé"}, {id:'c', text:"Para anúncios laterais"}, {id:'d', text:"Para o menu"}], correct: 'a', explanation: "<main> deve conter o conteúdo central que não se repete no site." },
        { question: "Qual tag é usada para conteúdo secundário (barra lateral)?", options: [{id:'a', text:"<aside>"}, {id:'b', text:"<sidebar>"}, {id:'c', text:"<side>"}, {id:'d', text:"<div>"}], correct: 'a', explanation: "A tag <aside> define conteúdo relacionado mas não vital (barras laterais)." },
        { question: "Qual a diferença entre <article> e <section>?", options: [{id:'a', text:"São iguais"}, {id:'b', text:"Article é independente, section é parte de algo maior"}, {id:'c', text:"Section é para música"}, {id:'d', text:"Article é para imagens"}], correct: 'b', explanation: "<article> pode existir sozinho, <section> depende do contexto." },
        { question: "Quando devemos usar a tag <div>?", options: [{id:'a', text:"Sempre que precisamos de uma caixa"}, {id:'b', text:"Apenas quando não existe outra tag semântica"}, {id:'c', text:"Para títulos"}, {id:'d', text:"Para parágrafos"}], correct: 'b', explanation: "Usa <div> apenas quando nenhuma tag semântica se aplica ao conteúdo." }
    ],
    'modulo-8': [
        { question: "O que significa o acrónimo ARIA?", options: [{id:'a', text:"Advanced Rich Internet Applications"}, {id:'b', text:"Accessible Rich Internet Applications"}, {id:'c', text:"Automated Rich Internet Apps"}, {id:'d', text:"All Real Interactive Apps"}], correct: 'b', explanation: "ARIA ajuda na acessibilidade de componentes complexos." },
        { question: "Qual é o primeiro princípio do WCAG?", options: [{id:'a', text:"Operável"}, {id:'b', text:"Percebível"}, {id:'c', text:"Compreensível"}, {id:'d', text:"Robusto"}], correct: 'b', explanation: "POUR: Percebível, Operável, Compreensível, Robusto." },
        { question: "Para que serve um 'skip link'?", options: [{id:'a', text:"Para saltar para outro site"}, {id:'b', text:"Para navegar diretamente para o conteúdo principal"}, {id:'c', text:"Para pular imagens"}, {id:'d', text:"Para ir para o rodapé"}], correct: 'b', explanation: "Skip links permitem aos utilizadores ignorar a navegação e ir direto ao conteúdo." },
        { question: "Como deve ser o texto alt de uma imagem decorativa?", options: [{id:'a', text:"Descritivo e longo"}, {id:'b', text:"Vazio (alt='')"}, {id:'c', text:"Uma palavra"}, {id:'d', text:"O nome do ficheiro"}], correct: 'b', explanation: "Imagens decorativas devem ter alt='' para serem ignoradas pelos leitores de ecrã." },
        { question: "Qual é a forma correta de navegar com o teclado?", options: [{id:'a', text:"Enter"}, {id:'b', text:"Tab"}, {id:'c', text:"Escape"}, {id:'d', text:"Delete"}], correct: 'b', explanation: "A tecla Tab move o foco entre elementos interativos da página." }
    ],
    'modulo-9': [
        { question: "Qual tag controla o título que aparece nos resultados de pesquisa?", options: [{id:'a', text:"<meta name='description'>"}, {id:'b', text:"<title>"}, {id:'c', text:"<h1>"}, {id:'d', text:"<link>"}], correct: 'b', explanation: "A tag <title> define o título que aparece nos resultados do Google." },
        { question: "Qual meta tag controla a imagem de partilha no Facebook?", options: [{id:'a', text:"og:title"}, {id:'b', text:"og:image"}, {id:'c', text:"twitter:card"}, {id:'d', text:"meta:thumb"}], correct: 'b', explanation: "og:image define a miniatura quando o link é partilhado." },
        { question: "Qual é o comprimento ideal do título SEO?", options: [{id:'a', text:"100 caracteres"}, {id:'b', text:"20 caracteres"}, {id:'c', text:"50-60 caracteres"}, {id:'d', text:"150 caracteres"}], correct: 'c', explanation: "Títulos entre 50-60 caracteres são exibidos completamente nos resultados." },
        { question: "O que faz a meta tag robots?", options: [{id:'a', text:"Define cores do site"}, {id:'b', text:"Controla se o Google indexa a página"}, {id:'c', text:"Cria um menu"}, {id:'d', text:"Adiciona JavaScript"}], correct: 'b', explanation: "meta name='robots' controla a indexação e seguimento de links." },
        { question: "Para que serve o atributo 'rel=canonical'?", options: [{id:'a', text:"Para criar links"}, {id:'b', text:"Para evitar conteúdo duplicado"}, {id:'c', text:"Para adicionar CSS"}, {id:'d', text:"Para criar formulários"}], correct: 'b', explanation: "O link canonical indica a versão preferida quando há conteúdo duplicado." }
    ],
    'modulo-10': [
        { question: "O que faz o atributo 'defer' na tag script?", options: [{id:'a', text:"Executa o script imediatamente"}, {id:'b', text:"Executa o script após o HTML ser parseado"}, {id:'c', text:"Bloqueia o carregamento"}, {id:'d', text:"Remove o script"}], correct: 'b', explanation: "defer executa o script depois de todo o HTML estar pronto." },
        { question: "O que faz o Lazy Loading em imagens?", options: [{id:'a', text:"Comprime automaticamente"}, {id:'b', text:"Adia o carregamento até a imagem estar perto da viewport"}, {id:'c', text:"Torna a imagem clicável"}, {id:'d', text:"Adiciona animação"}], correct: 'b', explanation: "Lazy loading melhora performance carregando apenas imagens visíveis." },
        { question: "Para que serve a tag 'link rel=preload'?", options: [{id:'a', text:"Para criar um menu"}, {id:'b', text:"Para carregar antecipadamente recursos críticos"}, {id:'c', text:"Para adicionar CSS"}, {id:'d', text:"Para criar imagens"}], correct: 'b', explanation: "preload diz ao browser para carregar recursos antecipadamente." },
        { question: "O que significa 'Above the Fold'?", options: [{id:'a', text:"Conteúdo após o rodapé"}, {id:'b', text:"Conteúdo visível sem scroll inicial"}, {id:'c', text:"Imagens grandes"}, {id:'d', text:"Vídeos em loop"}], correct: 'b', explanation: "Above the Fold é o conteúdo visível sem precisar de scroll." },
        { question: "Qual atributo prioriza o carregamento de um recurso?", options: [{id:'a', text:"priority"}, {id:'b', text:"fetchpriority"}, {id:'c', text:"importance"}, {id:'d', text:"preload"}], correct: 'b', explanation: "fetchpriority permite definir prioridade de carregamento (high/low)." }
    ],
    'modulo-11': [
        { question: "Qual atributo define o idioma principal do documento HTML?", options: [{id:'a', text:"lang"}, {id:'b', text:"language"}, {id:'c', text:"xml:lang"}, {id:'d', text:"charset"}], correct: 'a', explanation: "O atributo lang na tag html define o idioma principal (ex: lang='pt-PT')." },
        { question: "Qual codificação de caracteres suporta acentos portugueses?", options: [{id:'a', text:"ASCII"}, {id:'b', text:"ISO-8859-1"}, {id:'c', text:"UTF-8"}, {id:'d', text:"UTF-16"}], correct: 'c', explanation: "UTF-8 suporta todos os caracteres portugueses e muitos idiomas." },
        { question: "Qual valor de dir atribui a idiomas lidos da direita para a esquerda?", options: [{id:'a', text:"left"}, {id:'b', text:"reverse"}, {id:'c', text:"rtl"}, {id:'d', text:"backwards"}], correct: 'c', explanation: "dir='rtl' define direção da direita para a esquerda (árabe, hebraico)." },
        { question: "Para que serve o atributo 'translate' em elementos?", options: [{id:'a', text:"Para traduzir automaticamente"}, {id:'b', text:"Para indicar se o conteúdo deve ser traduzido"}, {id:'c', text:"Para criar traduções"}, {id:'d', text:"Para carregar ficheiros de idioma"}], correct: 'b', explanation: "translate='no' indica que o conteúdo não deve ser traduzido." },
        { question: "Qual é a boa prática para sites em múltiplos idiomas?", options: [{id:'a', text:"Usar a mesma URL para todos"}, {id:'b', text:"Usar o atributo hreflang nas links"}, {id:'c', text:"Ignorar o idioma"}, {id:'d', text:"Usar apenas imagens"}], correct: 'b', explanation: "hreflang indica aos motores de busca as versões em diferentes idiomas." }
    ],
    'modulo-12': [
        { question: "O que são Dados Estruturados?", options: [{id:'a', text:"CSS inline"}, {id:'b', text:"Marcação que explica o significado do conteúdo"}, {id:'c', text:"Imagens em alta resolução"}, {id:'d', text:"JavaScript inline"}], correct: 'b', explanation: "Dados estruturados ajudam os motores de busca a entender o conteúdo." },
        { question: "Qual vocabulário é usado para Dados Estruturados na web?", options: [{id:'a', text:"HTML5"}, {id:'b', text:"Schema.org"}, {id:'c', text:"XML"}, {id:'d', text:"YAML"}], correct: 'b', explanation: "Schema.org é o vocabulário padrão para microdados." },
        { question: "Qual formato de Dados Estruturados é preferido pelo Google?", options: [{id:'a', text:"Microdata"}, {id:'b', text:"RDFa"}, {id:'c', text:"JSON-LD"}, {id:'d', text:"XML"}], correct: 'c', explanation: "JSON-LD é o formato recomendado pelo Google para dados estruturados." },
        { question: "O que são Rich Snippets?", options: [{id:'a', text:"Imagens animadas"}, {id:'b', text:"Resultados de pesquisa melhorados com estrelas, preços, etc."}, {id:'c', text:"Vídeos incluídos"}, {id:'d', text:"Publicidade"}], correct: 'b', explanation: "Rich Snippets são resultados visuais melhorados nos motores de busca." },
        { question: "Qual elemento usa o atributo 'itemscope' em microdados?", options: [{id:'a', text:"Define um item"}, {id:'b', text:"Define uma propriedade"}, {id:'c', text:"Define um tipo"}, {id:'d', text:"Define uma URL"}], correct: 'a', explanation: "itemscope cria um grupo de pares de nome-valor (item)." }
    ],
    'modulo-13': [
        { question: "O que são Web Components?", options: [{id:'a', text:"Componentes de hardware para web"}, {id:'b', text:"Componentes reutilizáveis com Custom Elements, Shadow DOM e HTML Templates"}, {id:'c', text:"Biblioteca de ícones"}, {id:'d', text:"Plugins do browser"}], correct: 'b', explanation: "Web Components são standards nativos do browser para criar elementos reutilizáveis." },
        { question: "Para que serve a tag <template> em Web Components?", options: [{id:'a', text:"Para criar animações"}, {id:'b', text:"Para definir markup reutilizável sem renderizar"}, {id:'c', text:"Para adicionar estilos"}, {id:'d', text:"Para carregar scripts"}], correct: 'b', explanation: "<template> define markup que não é renderizado até ser usado via JavaScript." },
        { question: "O que é Shadow DOM?", options: [{id:'a', text:"Um tipo de animação"}, {id:'b', text:"Encapsulamento que isola estilos e markup"}, {id:'c', text:"Um elemento HTML"}, {id:'d', text:"Um servidor web"}], correct: 'b', explanation: "Shadow DOM permite que o componente tenha estilos isolados." },
        { question: "Como se cria um Custom Element em HTML?", options: [{id:'a', text:"Com a tag <custom>"}, {id:'b', text:"Registrando com customElements.define()"}, {id:'c', text:"Com CSS"}, {id:'d', text:"Com JSON"}], correct: 'b', explanation: "customElements.define() regista um novo elemento personalizado." },
        { question: "Qual é a vantagem principal dos Web Components?", options: [{id:'a', text:"São mais lentos que frameworks"}, {id:'b', text:"São nativos do browser, sem dependências externas"}, {id:'c', text:"Requerem instalação"}, {id:'d', text:"Não funcionam offline"}], correct: 'b', explanation: "Web Components usam APIs nativas do browser, sem bibliotecas." }
    ],
    'modulo-14': [
        { question: "O que é uma PWA (Progressive Web App)?", options: [{id:'a', text:"Um tipo de jogo online"}, {id:'b', text:"Um site com funcionalidades de aplicativo instalado"}, {id:'c', text:"Um banco de dados"}, {id:'d', text:"Um servidor"}], correct: 'b', explanation: "PWA é um site que funciona como aplicativo com instalação e offline." },
        { question: "Para que serve o ficheiro manifest.json numa PWA?", options: [{id:'a', text:"Para adicionar estilos"}, {id:'b', text:"Para definir o nome, ícones e comportamento de instalação"}, {id:'c', text:"Para criar animações"}, {id:'d', text:"Para validar HTML"}], correct: 'b', explanation: "O manifest.json define como a app aparece e se comporta quando instalada." },
        { question: "O que é um Service Worker?", options: [{id:'a', text:"Um plugin do browser"}, {id:'b', text:"Um script que funciona em background para cache e offline"}, {id:'c', text:"Um tipo de servidor"}, {id:'d', text:"Um editor de código"}], correct: 'b', explanation: "Service Workers permitem funcionamento offline e cache avançado." },
        { question: "Qual é o ciclo de vida de um Service Worker?", options: [{id:'a', text:"Install → Run → Delete"}, {id:'b', text:"Install → Activate → Fetch"}, {id:'c', text:"Start → Work → Stop"}, {id:'d', text:"Init → Execute → Finish"}], correct: 'b', explanation: "O ciclo Install → Activate → Fetch é o padrão dos Service Workers." },
        { question: "O que é o Cache em PWA?", options: [{id:'a', text:"Um tipo de erro"}, {id:'b', text:"Armazenamento local para carregamento offline"}, {id:'c', text:"Uma animação"}, {id:'d', text:"Um tipo de servidor"}], correct: 'b', explanation: "Cache guarda ficheiros localmente para funcionar sem internet." }
    ],
    'modulo-15': [
        { question: "Qual a melhor prática para separar responsabilidades (HTML, CSS, JS)?", options: [{id:'a', text:"Colocar tudo no mesmo ficheiro"}, {id:'b', text:"Separar em ficheiros distintos (index.html, style.css, script.js)"}, {id:'c', text:"Usar apenas CSS inline"}, {id:'d', text:"Usar apenas JavaScript inline"}], correct: 'b', explanation: "Separação em ficheiros distintos facilita manutenção e organização." },
        { question: "Para que servem os data attributes (data-*)?", options: [{id:'a', text:"Para estilizar elementos"}, {id:'b', text:"Para passar dados do HTML para o JavaScript"}, {id:'c', text:"Para criar animações"}, {id:'d', text:"Para validar formulários"}], correct: 'b', explanation: "Data attributes permitem guardar dados acessíveis via JavaScript." },
        { question: "O que é o DOM (Document Object Model)?", options: [{id:'a', text:"Um tipo de base de dados"}, {id:'b', text:"Uma representação em árvore do HTML manipulável por JS"}, {id:'c', text:"Um estilo CSS"}, {id:'d', text:"Um servidor"}], correct: 'b', explanation: "DOM é a representação do HTML que o JavaScript pode manipular." },
        { question: "Como se altera um estilo CSS com JavaScript?", options: [{id:'a', text:"Apenas com HTML"}, {id:'b', text:"Acessando element.style.propriedade"}, {id:'c', text:"Com CSS externo"}, {id:'d', text:"Com PHP"}], correct: 'b', explanation: "JavaScript pode alterar estilos via element.style.cor = 'blue'." },
        { question: "O que são eventos em JavaScript?", options: [{id:'a', text:"Erros de código"}, {id:'b', text:"Ações do utilizador que podem ser detectadas (clique, hover)"}, {id:'c', text:"Styles CSS"}, {id:'d', text:"Tags HTML"}], correct: 'b', explanation: "Eventos são ações como clique,keypress que podem.trigger funções." }
    ],
    'modulo-16': [
        { question: "Para que serve o W3C Validator?", options: [{id:'a', text:"Para criar websites"}, {id:'b', text:"Para verificar erros de HTML segundo padrões oficiais"}, {id:'c', text:"Para desenhar gráficos"}, {id:'d', text:"Para compilar JavaScript"}], correct: 'b', explanation: "W3C Validator verifica se o HTML segue os padrões oficiais." },
        { question: "O que é o Inspetor de Elementos do browser?", options: [{id:'a', text:"Um antivírus"}, {id:'b', text:"Uma ferramenta para ver e editar HTML/CSS em tempo real"}, {id:'c', text:"Um editor de imagens"}, {id:'d', text:"Um terminal"}], correct: 'b', explanation: "O Inspetor permite visualizar e testar alterações sem guardar ficheiros." },
        { question: "Onde aparecem os erros de JavaScript?", options: [{id:'a', text:"No HTML"}, {id:'b', text:"No Console do DevTools"}, {id:'c', text:"No CSS"}, {id:'d', text:"No servidor"}], correct: 'b', explanation: "O Console (F12) mostra erros de JavaScript e mensagens de debug." },
        { question: "O que é um 'bug' em programação?", options: [{id:'a', text:"Um vírus"}, {id:'b', text:"Um erro ou comportamento inesperado no código"}, {id:'c', text:"Um estilo CSS"}, {id:'d', text:"Um comentário"}], correct: 'b', explanation: "Bug é um erro que faz o software não funcionar como esperado." },
        { question: "O que é 'debugging' (depuração)?", options: [{id:'a', text:"Escrever código"}, {id:'b', text:"Encontrar e corrigir erros no código"}, {id:'c', text:"Criar websites"}, {id:'d', text:"Instalar programas"}], correct: 'b', explanation: "Debugging é o processo de identificar e resolver erros." }
    ],
    'modulo-17': [
        { question: "Qual é a convenção recomendada para nomes de ficheiros HTML?", options: [{id:'a', text:"camelCase"}, {id:'b', text:"kebab-case"}, {id:'c', text:"snake_case"}, {id:'d', text:"PascalCase"}], correct: 'b', explanation: "kebab-case (meu-ficheiro.html) é o padrão para ficheiros web." },
        { question: "O que significa versionamento semântico (SemVer)?", options: [{id:'a', text:"Número aleatório"}, {id:'b', text:"Formato Major.Minor.Patch (ex: 1.0.0)"}, {id:'c', text:"Apenas datas"}, {id:'d', text:"Nomes de animais"}], correct: 'b', explanation: "SemVer usa formato Major.Minor.Patch para versioning (1.2.3)." },
        { question: "Qual é a estrutura de pastas recomendada para projetos web?", options: [{id:'a', text:"Tudo na raiz"}, {id:'b', text:"Pasta css/, js/, images/, index.html"}, {id:'c', text:"Sem organização"}, {id:'d', text:"Uma pasta só"}], correct: 'b', explanation: "Organização em pastas facilita manutenção e encontra de ficheiros." },
        { question: "O que devem conter os comentários no código?", options: [{id:'a', text:"Apenas o quê"}, {id:'b', text:"O porquê das decisões (não apenas o quê)"}, {id:'c', text:"Nomes de pessoas"}, {id:'d', text:"Datas aleatórias"}], correct: 'b', explanation: "Comentar o 'porquê' ajuda futuros programadores a entender decisões." },
        { question: "Qual é o nome correto para ficheiros HTML usando kebab-case?", options: [{id:'a', text:"meuSite.html"}, {id:'b', text:"meu-site.html"}, {id:'c', text:"meu_site.html"}, {id:'d', text:"MeuSite.html"}], correct: 'b', explanation: "kebab-case usa hífens: meu-site.html, estilo.css, script.js." }
    ],
    'modulo-18': [
        { question: "O que é o Localhost?", options: [{id:'a', text:"Um site público"}, {id:'b', text:"O servidor local no teu próprio computador"}, {id:'c', text:"Um domínio pago"}, {id:'d', text:"Um email"}], correct: 'b', explanation: "Localhost (127.0.0.1) é o teu computador a servir ficheiros localmente." },
        { question: "Para que serve o DNS?", options: [{id:'a', text:"Para estilizar páginas"}, {id:'b', text:"Para traduzir nomes de domínio em endereços IP"}, {id:'c', text:"Para criar animações"}, {id:'d', text:"Para validar formulários"}], correct: 'b', explanation: "DNS traduz nomes como google.com em endereços IP numéricos." },
        { question: "Qual serviço permite hospedar sites estáticos gratuitamente?", options: [{id:'a', text:"Excel"}, {id:'b', text:"GitHub Pages"}, {id:'c', text:"Word"}, {id:'d', text:"Paint"}], correct: 'b', explanation: "GitHub Pages oferece hosting gratuito para sites estáticos." },
        { question: "O que é 'deploy' de um site?", options: [{id:'a', text:"Apagar ficheiros"}, {id:'b', text:"Enviar ficheiros do computador para o servidor"}, {id:'c', text:"Criar uma pasta"}, {id:'d', text:"Instalar programas"}], correct: 'b', explanation: "Deploy é o processo de publicar o site num servidor." },
        { question: "O que é um domínio?", options: [{id:'a', text:"Um tipo de erro"}, {id:'b', text:"O endereço único do teu site (ex: exemplo.com)"}, {id:'c', text:"Um estilo CSS"}, {id:'d', text:"Um servidor"}], correct: 'b', explanation: "Domínio é o endereço (ex: google.com) que as pessoas escrevem." }
    ],
    'modulo-19': [
        { question: "O que é o Google Lighthouse?", options: [{id:'a', text:"Um servidor"}, {id:'b', text:"Uma ferramenta de auditoria para performance, acessibilidade e SEO"}, {id:'c', text:"Um editor de texto"}, {id:'d', text:"Um antivirus"}], correct: 'b', explanation: "Lighthouse audita performance, acessibilidade, SEO e PWA." },
        { question: "Qual é o valor ideal de Performance no Lighthouse?", options: [{id:'a', text:"0-50"}, {id:'b', text:"90-100"}, {id:'c', text:"20-30"}, {id:'d', text:"50-60"}], correct: 'b', explanation: "Uma pontuação de 90-100 é considerada excelente." },
        { question: "O que o SEO no Lighthouse avalia?", options: [{id:'a', text:"As cores do site"}, {id:'b', text:"Meta tags, estrutura de títulos e acessibilidade"}, {id:'c', text:"A velocidade da internet"}, {id:'d', text:"O tamanho das imagens"}], correct: 'b', explanation: "SEO avalia elementos que afetam o ranking nos motores de busca." },
        { question: "O que significa Core Web Vitals?", options: [{id:'a', text:"Avaliações visuais"}, {id:'b', text:"Métricas de velocidade e interactivity (LCP, FID, CLS)"}, {id:'c', text:"Cores do site"}, {id:'d', text:"Imagens"}], correct: 'b', explanation: "Core Web Vitals são métricas do Google para experiência do utilizador." },
        { question: "Como melhorar a acessibilidade (a11y)?", options: [{id:'a', text:"Usar apenas imagens"}, {id:'b', text:"Usar texto alternativo, estrutura semântica e navegabilidade por teclado"}, {id:'c', text:"Usar cores brilhantes"}, {id:'d', text:"Remover todos os links"}], correct: 'b', explanation: "Acessibilidade requer alt texts, estrutura semântica e navegação por Tab." }
    ],
    'modulo-20': [
        { question: "O que é necessário para criar um projeto final com múltiplas páginas?", options: [{id:'a', text:"Um banco de dados"}, {id:'b', text:"Navegação com links entre páginas"}, {id:'c', text:"Apenas JavaScript"}, {id:'d', text:"Um servidor pago"}], correct: 'b', explanation: "Links entre páginas criam a navegação do site." },
        { question: "Qual é a estrutura básica de um portfólio profissional?", options: [{id:'a', text:"Apenas texto"}, {id:'b', text:"Página inicial, projetos, contacto e sobre"}, {id:'c', text:"Uma página só"}, {id:'d', text:"Apenas imagens"}], correct: 'b', explanation: "Um portfólio típico tem: início, projetos, sobre e contacto." },
        { question: "O que deve incluir um bom projeto para portfólio?", options: [{id:'a', text:"Copiar código de outros"}, {id:'b', text:"Código original, explicação do que faz e código limpo"}, {id:'c', text:"Apenas capturas de ecrã"}, {id:'d', text:"Nenhum código"}], correct: 'b', explanation: "Projetos devem mostrar código original, explicação e boas práticas." },
        { question: "Qual o próximo passo após aprender HTML?", options: [{id:'a', text:"Parar de aprender"}, {id:'b', text:"Aprender CSS para estilizar e JavaScript para interatividade"}, {id:'c', text:"ApenasHTML já é suficiente"}, {id:'d', text:"Esquecer o curso"}], correct: 'b', explanation: "CSS e JavaScript complementam HTML para criar sites completos." },
        { question: "O que significa ser um Full-Stack Developer?", options: [{id:'a', text:"Só front-end"}, {id:'b', text:"Desenvolver tanto front-end como back-end"}, {id:'c', text:"Apenas design"}, {id:'d', text:"Apenas base de dados"}], correct: 'b', explanation: "Full-Stack domina tanto a interface (front) como o servidor (back)." }
    ]
};

if (!window.QUIZ_DATA) window.QUIZ_DATA = {};
Object.assign(window.QUIZ_DATA, QUIZ_DATA_HTML);